/* Lexiphon word lists, second set. Each row names a word that real copy uses, and what each archetype would say in its place.
   The first set is in studio.js. Rules for every row:
   - the swap keeps the claim: a near-synonym, never a stronger or weaker one
   - no replacement word appears in the house slop lists (Tier 1 or Tier 2)
   - "a|b" gives a voice two candidates, the first being its default; the visitor can pick in the thesaurus popover
   - "!" drops the word; "base:3sg:past:ing" spells out a verb that does not inflect regularly (and any verb that doubles
     its last consonant); a phrase inflects its first word
   Guards: "vo" a verb followed straight by its object, "np" a verb followed by a determiner and a noun phrase,
   "nn" a noun or adjective that must follow an article or adjective, "adv" an adverb followed straight by its word.
   Rows whose source word is itself on a slop list exist to take that word out: each voice offers its own plain choice. */
var LEX_EXTRA = [
  /* verbs, plain */
  {p:"v", src:["provide"], g:"vo", skip:["that"], alt:{Caregiver:"give:gives:gave:giving", Ruler:"supply:supplies:supplied:supplying", Sage:"furnish"}},
  {p:"v", src:["offer"], g:"np", alt:{Ruler:"extend", Lover:"present", Caregiver:"give:gives:gave:giving", Sage:"put forward:puts forward:put forward:putting forward"}},
  {p:"v", src:["support"], g:"np", alt:{Caregiver:"look after:looks after:looked after:looking after", Hero:"back", Sage:"assist", "Regular Guy/Gal":"stand by:stands by:stood by:standing by"}},
  {p:"v", src:["manage"], g:"np", alt:{Ruler:"oversee:oversees:oversaw:overseeing", Sage:"administer", "Regular Guy/Gal":"handle"}},
  {p:"v", src:["maintain"], g:"np", alt:{Ruler:"uphold", Sage:"preserve", Caregiver:"look after:looks after:looked after:looking after", "Regular Guy/Gal":"keep up:keeps up:kept up:keeping up"}},
  {p:"v", src:["achieve"], g:"np", alt:{Hero:"accomplish", Ruler:"attain", Explorer:"reach", "Regular Guy/Gal":"pull off:pulls off:pulled off:pulling off", Jester:"nail"}},
  {p:"v", src:["develop"], g:"np", alt:{Creator:"fashion", "Regular Guy/Gal":"put together:puts together:put together:putting together"}},
  {p:"v", src:["implement"], g:"vo", alt:{Ruler:"enact", Hero:"carry out:carries out:carried out:carrying out", "Regular Guy/Gal":"put in place:puts in place:put in place:putting in place", Sage:"apply"}},
  {p:"v", src:["launch"], g:"np", alt:{Hero:"roll out:rolls out:rolled out:rolling out", Magician:"unveil", Ruler:"introduce", "Regular Guy/Gal":"put out:puts out:put out:putting out"}},
  {p:"v", src:["lead:leads:led:leading"], g:"np", alt:{Hero:"head", Ruler:"direct", "Regular Guy/Gal":"run:runs:ran:running", Caregiver:"guide"}},
  {p:"v", src:["guide"], g:"np", alt:{Explorer:"steer", Ruler:"direct", Caregiver:"accompany:accompanies:accompanied:accompanying", Magician:"lead:leads:led:leading"}},
  {p:"v", src:["enhance"], g:"np", alt:{Sage:"refine", Creator:"polish", Hero:"strengthen", Lover:"enrich", Ruler:"upgrade"}},
  {p:"v", src:["boost"], g:"np", alt:{Sage:"raise", Ruler:"lift", "Regular Guy/Gal":"push up:pushes up:pushed up:pushing up", Hero:"drive up:drives up:drove up:driving up"}},
  {p:"v", src:["require"], g:"vo", alt:{Ruler:"demand", "Regular Guy/Gal":"call for:calls for:called for:calling for", Sage:"necessitate"}},
  {p:"v", src:["allow"], g:"np", alt:{Ruler:"permit:permits:permitted:permitting"}},
  {p:"v", src:["begin:begins:began:beginning"], skip:["with","to"], alt:{Explorer:"set out:sets out:set out:setting out", Ruler:"commence", Sage:"initiate", Jester:"get going:gets going:got going:getting going"}},
  {p:"v", src:["finish"], g:"np", alt:{Ruler:"complete", "Regular Guy/Gal":"wrap up:wraps up:wrapped up:wrapping up", Sage:"conclude"}},
  {p:"v", src:["prove:proves:proved:proving"], skip:["to"], alt:{Sage:"demonstrate", Ruler:"establish", "Regular Guy/Gal":"show:shows:showed:showing"}},
  {p:"v", src:["confirm"], g:"vo", skip:["that"], alt:{Sage:"verify:verifies:verified:verifying", Ruler:"validate", "Regular Guy/Gal":"double-check"}},
  {p:"v", src:["measure"], g:"np", alt:{Sage:"gauge", Ruler:"quantify:quantifies:quantified:quantifying"}},
  {p:"v", src:["analyse:analyses:analysed:analysing","analyze:analyzes:analyzed:analyzing"], g:"vo", alt:{Sage:"examine", Ruler:"assess", Explorer:"probe", "Regular Guy/Gal":"look into:looks into:looked into:looking into"}},
  {p:"v", src:["review"], g:"np", alt:{Sage:"examine", Ruler:"audit", "Regular Guy/Gal":"go through:goes through:went through:going through"}},
  {p:"v", src:["track"], g:"np", alt:{Ruler:"monitor", Explorer:"trace", Sage:"record"}},
  {p:"v", src:["share"], g:"np", alt:{Caregiver:"pass on:passes on:passed on:passing on", Ruler:"distribute", Explorer:"spread:spreads:spread:spreading"}},
  {p:"v", src:["connect"], g:"vo", skip:["to","with"], alt:{Ruler:"link", Magician:"bridge", Caregiver:"bring together:brings together:brought together:bringing together"}},
  {p:"v", src:["answer"], g:"np", skip:["for"], alt:{Ruler:"address", "Regular Guy/Gal":"reply to:replies to:replied to:replying to"}},
  {p:"v", src:["win:wins:won:winning"], g:"np", alt:{Hero:"claim", Outlaw:"seize", Ruler:"secure", "Regular Guy/Gal":"land"}},
  {p:"v", src:["avoid"], g:"vo", alt:{Sage:"sidestep", Outlaw:"dodge", Caregiver:"steer clear of:steers clear of:steered clear of:steering clear of"}},
  {p:"v", src:["prevent"], g:"vo", alt:{Ruler:"forestall", Hero:"block", Caregiver:"guard against:guards against:guarded against:guarding against", Sage:"preclude"}},
  {p:"v", src:["remove"], g:"vo", alt:{Sage:"eliminate", "Regular Guy/Gal":"take out:takes out:took out:taking out", Outlaw:"strip out:strips out:stripped out:stripping out"}},
  {p:"v", src:["simplify:simplifies:simplified:simplifying"], g:"vo", alt:{Sage:"distil:distils:distilled:distilling", Creator:"pare back:pares back:pared back:paring back"}},
  {p:"v", src:["strengthen"], g:"vo", alt:{Hero:"fortify:fortifies:fortified:fortifying", Ruler:"reinforce", Sage:"consolidate"}},
  {p:"v", src:["expand"], g:"vo", alt:{Explorer:"widen", Sage:"broaden", Ruler:"extend"}},
  {p:"v", src:["teach:teaches:taught:teaching"], g:"np", alt:{Sage:"instruct", Caregiver:"coach", "Regular Guy/Gal":"show:shows:showed:showing", Explorer:"guide"}},
  {p:"v", src:["celebrate"], g:"np", alt:{Jester:"toast", Hero:"honour", Ruler:"mark", Lover:"savour"}},
  {p:"v", src:["introduce"], g:"np", alt:{Ruler:"present", Explorer:"unveil", "Regular Guy/Gal":"bring in:brings in:brought in:bringing in", Magician:"reveal"}},
  {p:"v", src:["discuss"], g:"np", alt:{"Regular Guy/Gal":"talk over:talks over:talked over:talking over", Ruler:"review", Caregiver:"talk through:talks through:talked through:talking through"}},
  {p:"v", src:["consider"], g:"np", alt:{Sage:"weigh", "Regular Guy/Gal":"think about:thinks about:thought about:thinking about"}},
  {p:"v", src:["describe"], g:"np", alt:{Lover:"portray", Ruler:"outline", "Regular Guy/Gal":"talk about:talks about:talked about:talking about"}},
  {p:"v", src:["combine"], g:"np", alt:{Creator:"blend", Magician:"fuse", Ruler:"consolidate", "Regular Guy/Gal":"mix"}},
  {p:"v", src:["reach"], g:"np", alt:{Hero:"hit:hits:hit:hitting", Sage:"attain", "Regular Guy/Gal":"get to:gets to:got to:getting to"}},
  {p:"v", src:["audit"], g:"np", alt:{Sage:"examine", Ruler:"inspect", "Regular Guy/Gal":"go through:goes through:went through:going through"}},
  {p:"v", src:["rewrite:rewrites:rewrote:rewriting"], g:"vo", alt:{Creator:"recast:recasts:recast:recasting", Sage:"revise", "Regular Guy/Gal":"redo:redoes:redid:redoing", Lover:"reshape"}},
  {p:"v", src:["draft"], g:"np", alt:{Creator:"sketch", Sage:"compose", Ruler:"prepare"}},
  {p:"v", src:["trace"], g:"vo", skip:["to"], alt:{Sage:"follow", Explorer:"track", Ruler:"establish"}},
  {p:"v", src:["raise"], g:"np", alt:{Ruler:"lift", Hero:"hoist", "Regular Guy/Gal":"bump up:bumps up:bumped up:bumping up"}},
  {p:"v", src:["handle"], g:"np", alt:{Ruler:"manage", Caregiver:"look after:looks after:looked after:looking after", Hero:"take on:takes on:took on:taking on", Sage:"deal with:deals with:dealt with:dealing with"}},
  /* verbs whose source word is on a slop list */
  {p:"v", src:["leverage"], g:"vo", alt:{Sage:"apply|employ", Ruler:"deploy", Hero:"wield", "Regular Guy/Gal":"use", Explorer:"draw on:draws on:drew on:drawing on", Magician:"channel", Creator:"work with:works with:worked with:working with", Caregiver:"rely on:relies on:relied on:relying on"}},
  {p:"v", src:["utilise:utilises:utilised:utilising","utilize:utilizes:utilized:utilizing"], g:"vo", alt:{"Regular Guy/Gal":"use", Sage:"apply", Ruler:"deploy", Hero:"wield", Explorer:"draw on:draws on:drew on:drawing on", Creator:"work with:works with:worked with:working with", Caregiver:"rely on:relies on:relied on:relying on"}},
  {p:"v", src:["elevate"], g:"vo", alt:{Ruler:"raise", Hero:"lift", Sage:"improve", "Regular Guy/Gal":"boost"}},
  {p:"v", src:["empower"], g:"vo", alt:{Caregiver:"equip:equips:equipped:equipping", Sage:"enable"}},
  {p:"v", src:["foster"], g:"vo", alt:{Caregiver:"encourage", Ruler:"promote", "Regular Guy/Gal":"build:builds:built:building", Sage:"cultivate"}},
  {p:"v", src:["unlock"], g:"vo", alt:{Explorer:"open up:opens up:opened up:opening up", Magician:"release", Hero:"free", Ruler:"realise"}},
  {p:"v", src:["craft"], g:"vo", alt:{Creator:"shape", Sage:"compose", Lover:"fashion", "Regular Guy/Gal":"put together:puts together:put together:putting together", Ruler:"build:builds:built:building"}},
  {p:"v", src:["harness"], g:"vo", alt:{Sage:"apply", Hero:"command", "Regular Guy/Gal":"use", Explorer:"tap:taps:tapped:tapping", Magician:"channel", Ruler:"direct"}},
  {p:"v", src:["spearhead"], g:"vo", alt:{Hero:"lead:leads:led:leading", Ruler:"direct", Explorer:"pioneer", "Regular Guy/Gal":"head up:heads up:headed up:heading up"}},
  {p:"v", src:["showcase"], g:"vo", alt:{Creator:"display", Lover:"present", Jester:"show off:shows off:showed off:showing off", Sage:"demonstrate", "Regular Guy/Gal":"show:shows:showed:showing"}},
  {p:"v", src:["optimise:optimises:optimised:optimising","optimize:optimizes:optimized:optimizing"], g:"vo", alt:{Sage:"tune", "Regular Guy/Gal":"tweak", Creator:"fine-tune", Hero:"sharpen", Ruler:"refine"}},
  {p:"v", src:["streamline"], g:"vo", alt:{Ruler:"rationalise", Sage:"simplify:simplifies:simplified:simplifying", Creator:"pare back:pares back:pared back:paring back", "Regular Guy/Gal":"trim:trims:trimmed:trimming"}},
  {p:"v", src:["revolutionise:revolutionises:revolutionised:revolutionising","revolutionize:revolutionizes:revolutionized:revolutionizing"], g:"vo", alt:{Outlaw:"overturn", Ruler:"overhaul", Sage:"reshape", Hero:"upend", Magician:"transform"}},
  {p:"v", src:["supercharge","turbocharge"], g:"vo", alt:{Hero:"power up:powers up:powered up:powering up", Jester:"rev up:revs up:revved up:revving up", "Regular Guy/Gal":"boost", Ruler:"accelerate"}},
  {p:"v", src:["underscore"], g:"vo", alt:{Sage:"stress", Ruler:"emphasise"}},
  {p:"v", src:["highlight"], g:"vo", alt:{Sage:"point out:points out:pointed out:pointing out", Creator:"pick out:picks out:picked out:picking out", "Regular Guy/Gal":"flag:flags:flagged:flagging"}},
  /* adjectives, plain */
  {p:"a", src:["reliable"], alt:{Caregiver:"dependable", Ruler:"consistent", Hero:"steadfast", Sage:"trustworthy", "Regular Guy/Gal":"solid"}},
  {p:"a", src:["fast"], g:"nn", alt:{Explorer:"swift", Hero:"rapid", Jester:"zippy", "Regular Guy/Gal":"speedy", Ruler:"prompt"}},
  {p:"a", src:["clear"], g:"nn", alt:{Sage:"lucid", Ruler:"explicit", Innocent:"plain", "Regular Guy/Gal":"straight", Hero:"unmistakable", Creator:"crisp"}},
  {p:"a", src:["powerful"], alt:{Hero:"mighty", Ruler:"commanding", Sage:"potent"}},
  {p:"a", src:["bold"], alt:{Hero:"daring", Explorer:"adventurous", "Regular Guy/Gal":"gutsy"}},
  {p:"a", src:["creative"], alt:{Creator:"inventive", Magician:"imaginative", Jester:"playful"}},
  {p:"a", src:["unique"], skip:["selling"], alt:{Sage:"distinctive", Magician:"singular", "Regular Guy/Gal":"one-off", Lover:"special"}},
  {p:"a", src:["modern"], alt:{Ruler:"current", Explorer:"contemporary", "Regular Guy/Gal":"up-to-date"}},
  {p:"a", src:["complex"], alt:{Sage:"involved", Explorer:"layered"}},
  {p:"a", src:["famous"], alt:{Hero:"renowned", Sage:"noted", Ruler:"eminent", "Regular Guy/Gal":"well-known"}},
  {p:"a", src:["successful"], alt:{Hero:"triumphant", Ruler:"accomplished", "Regular Guy/Gal":"winning"}},
  {p:"a", src:["careful"], alt:{Sage:"painstaking", Ruler:"exact", Caregiver:"attentive", "Regular Guy/Gal":"thorough"}},
  {p:"a", src:["perfect"], g:"nn", alt:{Lover:"flawless", Creator:"ideal", Sage:"ideal", "Regular Guy/Gal":"spot-on"}},
  {p:"a", src:["global"], alt:{Explorer:"worldwide", Ruler:"international"}},
  {p:"a", src:["necessary"], alt:{Ruler:"essential", Sage:"required", "Regular Guy/Gal":"needed"}},
  {p:"a", src:["useful"], alt:{"Regular Guy/Gal":"handy", Sage:"practical", Explorer:"worthwhile"}},
  {p:"a", src:["hard"], g:"nn", alt:{Sage:"demanding", "Regular Guy/Gal":"tough", Hero:"punishing", Outlaw:"brutal", Explorer:"testing"}},
  {p:"a", src:["wide"], g:"nn", alt:{Explorer:"broad", Ruler:"extensive"}},
  {p:"a", src:["final"], g:"nn", alt:{Ruler:"closing", "Regular Guy/Gal":"last", Sage:"concluding"}},
  {p:"a", src:["complete"], g:"nn", alt:{Ruler:"entire", Sage:"thorough", "Regular Guy/Gal":"full", Hero:"total"}},
  {p:"a", src:["excellent"], alt:{Ruler:"first-rate", Hero:"outstanding", Lover:"superb", Jester:"ace", "Regular Guy/Gal":"top"}},
  {p:"a", src:["amazing"], alt:{Explorer:"astonishing", Magician:"marvellous", Lover:"wonderful", "Regular Guy/Gal":"brilliant", Sage:"remarkable"}},
  {p:"a", src:["helpful"], alt:{Caregiver:"supportive", "Regular Guy/Gal":"handy", Ruler:"useful"}},
  /* adjectives whose source word is on a slop list */
  {p:"a", src:["compelling"], alt:{Sage:"persuasive", Ruler:"convincing", Explorer:"absorbing", "Regular Guy/Gal":"good", Outlaw:"gripping"}},
  {p:"a", src:["impactful"], alt:{Sage:"effective", Hero:"powerful", Outlaw:"hard-hitting", "Regular Guy/Gal":"punchy"}},
  {p:"a", src:["innovative"], alt:{Creator:"inventive", Explorer:"pioneering", Sage:"original", Ruler:"modern", "Regular Guy/Gal":"fresh"}},
  {p:"a", src:["robust"], alt:{Ruler:"sound", Sage:"dependable", Hero:"sturdy", Caregiver:"resilient", "Regular Guy/Gal":"solid"}},
  {p:"a", src:["seamless"], alt:{"Regular Guy/Gal":"smooth", Ruler:"uninterrupted"}},
  {p:"a", src:["cutting-edge"], alt:{Explorer:"pioneering", Ruler:"modern", Sage:"up-to-date", "Regular Guy/Gal":"latest"}},
  {p:"a", src:["state-of-the-art"], alt:{"Regular Guy/Gal":"latest", Ruler:"modern", Sage:"current"}},
  {p:"a", src:["world-class"], alt:{Ruler:"first-rate", Sage:"exemplary", "Regular Guy/Gal":"top-quality"}},
  {p:"a", src:["comprehensive"], alt:{Sage:"thorough", Ruler:"complete", "Regular Guy/Gal":"full", Explorer:"wide-ranging", Caregiver:"all-round"}},
  {p:"a", src:["diverse"], alt:{Sage:"varied", Explorer:"wide-ranging", Ruler:"assorted", "Regular Guy/Gal":"mixed"}},
  {p:"a", src:["vibrant"], alt:{Jester:"lively", Explorer:"colourful", Creator:"vivid", "Regular Guy/Gal":"busy"}},
  {p:"a", src:["stunning","breathtaking"], alt:{Lover:"exquisite", Creator:"striking", "Regular Guy/Gal":"lovely", Explorer:"magnificent", Ruler:"impressive", Sage:"remarkable"}},
  {p:"a", src:["passionate"], alt:{Lover:"devoted", Sage:"dedicated", Ruler:"committed", "Regular Guy/Gal":"keen", Jester:"mad keen"}},
  {p:"a", src:["proven"], alt:{Sage:"demonstrated", Hero:"tested", Ruler:"established", "Regular Guy/Gal":"solid"}},
  {p:"a", src:["groundbreaking","game-changing"], alt:{Explorer:"pioneering", Creator:"inventive", Ruler:"major"}},
  {p:"a", src:["transformative"], alt:{Magician:"far-reaching", Ruler:"major", "Regular Guy/Gal":"big"}},
  /* nouns, plain */
  {p:"n", src:["business"], g:"nn", skip:["case","model","plan","strategy","card","cards","leader","leaders","owner","owners","partner","process","processes","unit","units","school","analyst","development","objectives","goals","needs","growth","as","trip","travel","email"], alt:{Ruler:"enterprise", Hero:"firm", Sage:"organisation", Explorer:"venture"}},
  {p:"n", src:["challenge"], g:"nn", alt:{Sage:"difficulty:difficulties", "Regular Guy/Gal":"hurdle", Hero:"trial", Explorer:"obstacle"}},
  {p:"n", src:["opportunity"], alt:{Explorer:"opening", Hero:"chance", "Regular Guy/Gal":"chance", Ruler:"prospect", Sage:"possibility:possibilities"}},
  {p:"n", src:["benefit"], g:"nn", alt:{Sage:"advantage", "Regular Guy/Gal":"upside", Hero:"gain"}},
  {p:"n", src:["relationship"], alt:{Lover:"bond", "Regular Guy/Gal":"link", Sage:"association"}},
  {p:"n", src:["process"], g:"nn", alt:{Sage:"procedure", Ruler:"protocol", "Regular Guy/Gal":"routine:routines"}},
  {p:"n", src:["example"], g:"nn", alt:{Sage:"instance"}},
  {p:"n", src:["standard"], g:"nn", skip:["practice","approach","procedure","format","setup","template","rate","way","of"], alt:{Ruler:"benchmark", Hero:"bar:bars", "Regular Guy/Gal":"yardstick", Sage:"criterion:criteria"}},
  {p:"n", src:["claim"], g:"nn", alt:{Sage:"assertion", Ruler:"statement"}},
  {p:"n", src:["country:countries"], alt:{Explorer:"nation:nations"}},
  {p:"n", src:["industry:industries"], alt:{Ruler:"sector", Sage:"field", Explorer:"domain"}},
  {p:"n", src:["method"], alt:{Sage:"procedure", Ruler:"protocol", "Regular Guy/Gal":"way", Creator:"technique"}},
  {p:"n", src:["answer"], g:"nn", alt:{Sage:"resolution", Hero:"remedy:remedies", "Regular Guy/Gal":"fix:fixes"}},
  {p:"n", src:["danger"], alt:{Hero:"peril", Explorer:"hazard", Outlaw:"threat", Sage:"risk"}},
  {p:"n", src:["strength"], alt:{Hero:"might:might", Caregiver:"steadiness:steadiness", Sage:"force:forces"}},
  /* nouns whose source word is on a slop list */
  {p:"n", src:["solution"], alt:{"Regular Guy/Gal":"fix:fixes", Hero:"answer", Sage:"remedy:remedies"}},
  {p:"n", src:["stakeholder"], alt:{Ruler:"interested party:interested parties", "Regular Guy/Gal":"person involved:people involved"}},
  {p:"n", src:["journey"], g:"nn", alt:{Hero:"quest", Explorer:"expedition", "Regular Guy/Gal":"route", Sage:"path", Lover:"voyage"}},
  {p:"n", src:["landscape"], g:"nn", alt:{Sage:"field", Explorer:"terrain", "Regular Guy/Gal":"scene"}},
  {p:"n", src:["ecosystem"], g:"nn", alt:{Sage:"system", Ruler:"network"}},
  {p:"n", src:["insight"], alt:{Sage:"finding", "Regular Guy/Gal":"pointer", Explorer:"discovery:discoveries"}},
  {p:"n", src:["narrative"], alt:{Creator:"story:stories", Sage:"account", Lover:"tale", Ruler:"line"}},
  {p:"n", src:["engagement"], alt:{Sage:"involvement", "Regular Guy/Gal":"interest", Lover:"connection", Hero:"participation"}},
  {p:"n", src:["visibility"], alt:{Ruler:"profile", "Regular Guy/Gal":"presence", Sage:"exposure"}},
  {p:"n", src:["passion"], skip:["for","to"], alt:{Lover:"devotion", "Regular Guy/Gal":"enthusiasm", Sage:"commitment", Hero:"drive"}},
  {p:"n", src:["innovation"], g:"nn", alt:{Creator:"invention", Sage:"new thinking:new thinking"}},
  {p:"n", src:["offering"], alt:{"Regular Guy/Gal":"range:ranges", Ruler:"portfolio"}},
  /* adverbs and props: the plain and formal voices drop the filler */
  {p:"r", src:["obviously","undoubtedly","undeniably","arguably","essentially","basically"], g:"adv", alt:{Sage:"!", Ruler:"!", "Regular Guy/Gal":"!", Hero:"!"}},
  {p:"r", src:["quite"], g:"adv", alt:{"Regular Guy/Gal":"pretty", Sage:"rather", Ruler:"fairly"}},
  {p:"r", src:["completely"], g:"adv", alt:{Ruler:"fully", Hero:"utterly", "Regular Guy/Gal":"totally", Sage:"entirely", Explorer:"wholly"}},
  {p:"r", src:["usually"], g:"adv", alt:{Sage:"typically", "Regular Guy/Gal":"normally", Explorer:"commonly"}}
];

/* Third set: everyday copy words found missing when real paragraphs were tested. */
LEX_EXTRA = LEX_EXTRA.concat([
  {p:"v", src:["try:tries:tried:trying"], g:"np", skip:["to"], alt:{Sage:"test", Explorer:"sample", Hero:"attempt", Innocent:"test"}},
  {p:"v", src:["face"], g:"vo", alt:{Hero:"confront", Outlaw:"stare down:stares down:stared down:staring down"}},
  {p:"n", src:["error"], alt:{Sage:"mistake", Ruler:"fault", Outlaw:"blunder", "Regular Guy/Gal":"mistake"}},
  {p:"n", src:["detail"], alt:{Sage:"particular", Ruler:"point", Lover:"nuance", Creator:"touch:touches"}},
  {p:"n", src:["atmosphere"], alt:{Lover:"mood", Creator:"feel:feels", Sage:"ambience"}},
  {p:"n", src:["choice"], alt:{Sage:"option", "Regular Guy/Gal":"pick", Hero:"decision", Explorer:"path"}},
  {p:"n", src:["gift"], alt:{Ruler:"contribution", "Regular Guy/Gal":"donation", Caregiver:"donation"}},
  {p:"n", src:["shelter"], g:"nn", alt:{Caregiver:"refuge", Explorer:"haven", Hero:"sanctuary", Innocent:"safe place:safe places"}},
  {p:"n", src:["guest"], alt:{Ruler:"patron", Caregiver:"visitor", Explorer:"traveller", "Regular Guy/Gal":"visitor", Sage:"visitor"}},
  {p:"n", src:["price"], g:"nn", alt:{"Regular Guy/Gal":"cost", Sage:"cost", Ruler:"charge"}},
  {p:"n", src:["option"], alt:{Sage:"alternative", "Regular Guy/Gal":"choice", Ruler:"course", Explorer:"route"}},
  {p:"n", src:["growth"], alt:{Explorer:"expansion", Hero:"rise", Ruler:"increase", Lover:"flowering"}},
  {p:"n", src:["mission"], g:"nn", alt:{Sage:"purpose", Ruler:"remit", Hero:"cause", Magician:"calling", Caregiver:"purpose", Explorer:"quest"}},
  {p:"n", src:["vision"], g:"nn", alt:{Sage:"outlook", Explorer:"horizon", Hero:"ambition", Lover:"dream"}},
  {p:"n", src:["expertise"], alt:{Sage:"knowledge:knowledge", Hero:"mastery:mastery", "Regular Guy/Gal":"know-how:know-how", Ruler:"command:command"}},
  {p:"n", src:["support"], g:"nn", skip:["team","teams","staff","desk","centre","center","services","service","line","email","ticket","tickets","agent","agents","plan","plans","packages","package","contract","engineer","engineers","channel","channels","portal","hours","for","from"], alt:{Sage:"assistance", Caregiver:"help", Lover:"care", Hero:"backing"}},
  {p:"a", src:["warm"], skip:["up","weather","water","days"], alt:{"Regular Guy/Gal":"friendly", Jester:"cosy", Innocent:"kind", Lover:"tender", Caregiver:"gentle"}},
  {p:"a", src:["quiet"], alt:{Magician:"hushed", Lover:"peaceful", Caregiver:"restful", Innocent:"calm"}},
  {p:"a", src:["safe"], g:"nn", alt:{Innocent:"snug", Hero:"guarded", Caregiver:"sheltered", Outlaw:"locked-down"}},
  {p:"a", src:["clean"], g:"nn", alt:{Innocent:"fresh", Sage:"uncluttered", Lover:"spotless", Hero:"crisp"}}
]);

/* Additions for voices that the rows above and in studio.js leave thin. Keyed by part of speech and first source word;
   a voice that already has a word in the row keeps it. Same rules as above: near-synonyms only, none on the slop lists. */
var LEX_PATCH = {
  /* verbs, first set */
  "v:use":{Creator:"work with:works with:worked with:working with", Explorer:"draw on:draws on:drew on:drawing on", Magician:"channel", Caregiver:"rely on:relies on:relied on:relying on"},
  "v:make":{Lover:"fashion", Outlaw:"hammer out:hammers out:hammered out:hammering out", Jester:"whip up:whips up:whipped up:whipping up"},
  "v:get":{Innocent:"receive:receives:received:receiving"},
  "v:show":{Caregiver:"walk through:walks through:walked through:walking through"},
  "v:change":{Caregiver:"adjust", Explorer:"shift", Jester:"tweak"},
  "v:improve":{Explorer:"advance"},
  "v:check":{Caregiver:"go over:goes over:went over:going over", Creator:"inspect"},
  "v:choose":{Innocent:"pick", Outlaw:"hand-pick", Creator:"settle on:settles on:settled on:settling on"},
  "v:deliver":{Innocent:"bring:brings:brought:bringing", Lover:"present", Explorer:"carry:carries:carried:carrying"},
  "v:keep":{Innocent:"hold on to:holds on to:held on to:holding on to", Magician:"guard"},
  "v:start":{Innocent:"begin:begins:began:beginning", Creator:"set up:sets up:set up:setting up"},
  "v:want":{Innocent:"wish for:wishes for:wished for:wishing for", Creator:"hope for:hopes for:hoped for:hoping for", Caregiver:"hope for:hopes for:hoped for:hoping for", Jester:"fancy:fancies:fancied:fancying"},
  "v:build":{Innocent:"make:makes:made:making", Jester:"cobble together:cobbles together:cobbled together:cobbling together", Explorer:"construct"},
  "v:create":{Innocent:"make:makes:made:making", Jester:"cook up:cooks up:cooked up:cooking up", Lover:"fashion"},
  "v:explain":{Jester:"break down:breaks down:broke down:breaking down", Explorer:"map out:maps out:mapped out:mapping out", Magician:"unfold"},
  "v:explore":{Jester:"poke around in:pokes around in:poked around in:poking around in", Creator:"play with:plays with:played with:playing with"},
  "v:learn":{Jester:"soak up:soaks up:soaked up:soaking up", Magician:"glean"},
  "v:understand":{Innocent:"grasp", Creator:"grasp"},
  "v:fix":{Innocent:"put right:puts right:put right:putting right", Jester:"patch up:patches up:patched up:patching up", Creator:"repair"},
  "v:protect":{Innocent:"keep safe:keeps safe:kept safe:keeping safe", Outlaw:"shield", Explorer:"guard"},
  "v:love":{Innocent:"treasure", Magician:"prize"},
  "v:enjoy":{Caregiver:"appreciate", Outlaw:"relish"},
  "v:write":{Innocent:"jot down:jots down:jotted down:jotting down", Jester:"scribble", Caregiver:"put down:puts down:put down:putting down", Magician:"inscribe"},
  "v:reduce":{Innocent:"lessen", Outlaw:"slash"},
  "v:increase":{Outlaw:"crank up:cranks up:cranked up:cranking up", Jester:"ramp up:ramps up:ramped up:ramping up", Creator:"expand", Caregiver:"build up:builds up:built up:building up"},
  "v:give":{Lover:"bestow", Jester:"dish out:dishes out:dished out:dishing out", Outlaw:"hand out:hands out:handed out:handing out", Magician:"bestow"},
  "v:see":{Innocent:"notice", Caregiver:"notice"},
  "v:run":{Magician:"conduct"},
  "v:solve":{Innocent:"settle", Creator:"work out:works out:worked out:working out"},
  "v:stop":{Innocent:"end"},
  "v:replace":{Innocent:"swap:swaps:swapped:swapping", Explorer:"exchange"},
  /* adjectives, first set */
  "a:great":{Outlaw:"mighty", Magician:"marvellous", Explorer:"grand"},
  "a:big":{Innocent:"large"},
  "a:small":{Outlaw:"scrappy", Creator:"compact"},
  "a:new":{Caregiver:"fresh"},
  "a:simple":{Lover:"pared-back", Creator:"clean"},
  "a:difficult":{Innocent:"hard"},
  "a:quick":{Innocent:"fast", Creator:"nimble"},
  "a:important":{Innocent:"key", Magician:"weighty", Creator:"key"},
  "a:strong":{Innocent:"firm", Magician:"potent", Creator:"sturdy"},
  "a:interesting":{Lover:"engrossing"},
  "a:easy":{Explorer:"smooth"},
  "a:honest":{Jester:"upfront", Creator:"open", Caregiver:"sincere"},
  "a:smart":{Innocent:"bright", Jester:"clever", Caregiver:"sensible", Explorer:"shrewd"},
  "a:real":{Magician:"true", Caregiver:"true", Creator:"authentic"},
  "a:best":{Outlaw:"top", Explorer:"prime"},
  "a:boring":{Explorer:"bland", Creator:"flat", Caregiver:"dreary"},
  "a:many":{Innocent:"lots of", Caregiver:"plenty of", Explorer:"plenty of"},
  "a:friendly":{Magician:"genial"},
  "a:nice":{Creator:"pleasant"},
  "a:normal":{Innocent:"usual", Magician:"ordinary", Jester:"run-of-the-mill", Caregiver:"usual", Explorer:"typical"},
  "a:attractive":{Innocent:"pretty", Jester:"fetching", Caregiver:"pleasing", Explorer:"appealing"},
  "a:surprising":{Innocent:"unexpected", Caregiver:"unexpected", Explorer:"startling"},
  /* nouns, first set */
  "n:problem":{Explorer:"obstacle"},
  "n:idea":{Innocent:"thought", Lover:"notion", Caregiver:"suggestion"},
  "n:goal":{Creator:"aim"},
  "n:team":{Innocent:"group"},
  "n:customer":{Creator:"patron"},
  "n:company":{Innocent:"business", Outlaw:"operation", Jester:"shop"},
  "n:project":{Innocent:"piece of work:pieces of work", Outlaw:"job", Magician:"undertaking", Caregiver:"effort"},
  "n:result":{Jester:"upshot", Caregiver:"outcome"},
  "n:story":{Caregiver:"account"},
  "n:friend":{Outlaw:"ally", Explorer:"companion"},
  "n:expert":{Magician:"adept", Jester:"whizz:whizzes", Caregiver:"specialist", Creator:"master"},
  "n:approach":{Jester:"angle", Explorer:"route"},
  "n:plan":{Outlaw:"scheme", Jester:"game plan:game plans"},
  "n:tool":{Caregiver:"aid", Explorer:"gear:gear"},
  "n:success":{Outlaw:"win", Magician:"triumph", Caregiver:"good outcome:good outcomes", Creator:"achievement"},
  "r:quickly":{Creator:"briskly"},
  "r:about":{Innocent:"around", Caregiver:"around", Creator:"close to"},
  /* verbs, second set */
  "v:provide":{Innocent:"give:gives:gave:giving", Magician:"bestow"},
  "v:offer":{Innocent:"give:gives:gave:giving", Creator:"present"},
  "v:support":{Innocent:"help", Jester:"cheer on:cheers on:cheered on:cheering on", Outlaw:"back", Lover:"champion"},
  "v:manage":{Innocent:"look after:looks after:looked after:looking after", Outlaw:"run:runs:ran:running", Magician:"steer", Lover:"tend", Caregiver:"look after:looks after:looked after:looking after", Explorer:"steer"},
  "v:maintain":{Innocent:"keep up:keeps up:kept up:keeping up", Creator:"hold:holds:held:holding"},
  "v:achieve":{Innocent:"reach", Magician:"realise", Lover:"fulfil:fulfils:fulfilled:fulfilling", Caregiver:"reach", Outlaw:"smash"},
  "v:develop":{Outlaw:"hammer out:hammers out:hammered out:hammering out", Lover:"cultivate", Caregiver:"build up:builds up:built up:building up", Explorer:"pioneer"},
  "v:implement":{Outlaw:"push through:pushes through:pushed through:pushing through", Caregiver:"put into practice:puts into practice:put into practice:putting into practice", Explorer:"carry out:carries out:carried out:carrying out"},
  "v:launch":{Innocent:"start", Outlaw:"drop", Creator:"release", Explorer:"unveil"},
  "v:lead":{Outlaw:"head", Explorer:"head"},
  "v:guide":{Jester:"steer", Creator:"steer"},
  "v:enhance":{Innocent:"improve", Outlaw:"sharpen", Jester:"jazz up:jazzes up:jazzed up:jazzing up", Explorer:"build on:builds on:built on:building on"},
  "v:boost":{Innocent:"lift", Outlaw:"crank up:cranks up:cranked up:cranking up", Jester:"ramp up:ramps up:ramped up:ramping up", Magician:"amplify"},
  "v:require":{Innocent:"need", Outlaw:"demand", Lover:"ask for:asks for:asked for:asking for", Caregiver:"need"},
  "v:begin":{Innocent:"start", Outlaw:"kick off:kicks off:kicked off:kicking off", Caregiver:"start"},
  "v:finish":{Innocent:"end", Outlaw:"close out:closes out:closed out:closing out", Jester:"polish off:polishes off:polished off:polishing off", Lover:"complete", Creator:"complete", Explorer:"wrap up:wraps up:wrapped up:wrapping up"},
  "v:prove":{Innocent:"show:shows:showed:showing"},
  "v:confirm":{Caregiver:"check"},
  "v:analyse":{Innocent:"look at:looks at:looked at:looking at", Jester:"dissect", Lover:"study:studies:studied:studying", Caregiver:"look at:looks at:looked at:looking at", Creator:"examine"},
  "v:review":{Lover:"revisit", Caregiver:"look at:looks at:looked at:looking at", Creator:"revisit"},
  "v:track":{Innocent:"follow", Caregiver:"follow"},
  "v:share":{Innocent:"pass on:passes on:passed on:passing on", Jester:"pass round:passes round:passed round:passing round"},
  "v:connect":{Innocent:"join", Jester:"hook up:hooks up:hooked up:hooking up", Lover:"bring together:brings together:brought together:bringing together", Creator:"join", Explorer:"bridge"},
  "v:answer":{Innocent:"reply to:replies to:replied to:replying to"},
  "v:win":{Jester:"bag:bags:bagged:bagging", Explorer:"claim"},
  "v:avoid":{Innocent:"keep away from:keeps away from:kept away from:keeping away from", Jester:"duck", Lover:"shun", Creator:"sidestep", Explorer:"bypass"},
  "v:prevent":{Innocent:"stop", Outlaw:"head off:heads off:headed off:heading off", Magician:"ward off:wards off:warded off:warding off"},
  "v:remove":{Innocent:"take away:takes away:took away:taking away", Magician:"banish", Jester:"ditch", Caregiver:"clear away:clears away:cleared away:clearing away", Creator:"cut:cuts:cut:cutting"},
  "v:simplify":{Outlaw:"strip back:strips back:stripped back:stripping back", Jester:"boil down:boils down:boiled down:boiling down"},
  "v:strengthen":{Innocent:"firm up:firms up:firmed up:firming up", Outlaw:"toughen", Jester:"beef up:beefs up:beefed up:beefing up", Explorer:"reinforce"},
  "v:celebrate":{Innocent:"enjoy"},
  "v:discuss":{Innocent:"talk about:talks about:talked about:talking about", Outlaw:"hash out:hashes out:hashed out:hashing out", Jester:"chew over:chews over:chewed over:chewing over"},
  "v:consider":{Outlaw:"size up:sizes up:sized up:sizing up", Jester:"mull over:mulls over:mulled over:mulling over", Lover:"ponder", Magician:"contemplate", Caregiver:"think over:thinks over:thought over:thinking over", Explorer:"weigh up:weighs up:weighed up:weighing up"},
  "v:describe":{Outlaw:"lay out:lays out:laid out:laying out", Creator:"depict"},
  "v:combine":{Innocent:"join", Jester:"mash up:mashes up:mashed up:mashing up", Lover:"weave:weaves:wove:weaving"},
  "v:rewrite":{Jester:"rejig:rejigs:rejigged:rejigging", Caregiver:"redraft"},
  "v:draft":{Innocent:"write:writes:wrote:writing", Jester:"knock out:knocks out:knocked out:knocking out", Lover:"pen:pens:penned:penning", Explorer:"outline"},
  "v:raise":{Innocent:"lift"},
  "v:handle":{Innocent:"look after:looks after:looked after:looking after", Outlaw:"deal with:deals with:dealt with:dealing with"},
  "v:leverage":{Innocent:"use", Outlaw:"wield", Lover:"draw on:draws on:drew on:drawing on"},
  "v:utilise":{Innocent:"use", Outlaw:"use"},
  "v:elevate":{Innocent:"lift", Outlaw:"lift", Lover:"refine"},
  "v:empower":{Innocent:"help", Outlaw:"arm", Creator:"equip:equips:equipped:equipping", Magician:"enable"},
  "v:foster":{Innocent:"encourage", Magician:"awaken"},
  "v:unlock":{Innocent:"open", Outlaw:"crack open:cracks open:cracked open:cracking open", Creator:"open up:opens up:opened up:opening up"},
  "v:craft":{Innocent:"make:makes:made:making", Outlaw:"hammer out:hammers out:hammered out:hammering out", Jester:"knock together:knocks together:knocked together:knocking together", Explorer:"construct", Magician:"conjure"},
  "v:showcase":{Innocent:"show:shows:showed:showing", Outlaw:"flaunt", Magician:"unveil", Explorer:"present"},
  "v:optimise":{Innocent:"improve", Jester:"fine-tune", Lover:"perfect", Magician:"refine", Caregiver:"improve", Explorer:"hone"},
  "v:streamline":{Innocent:"simplify:simplifies:simplified:simplifying", Outlaw:"strip back:strips back:stripped back:stripping back", Jester:"trim:trims:trimmed:trimming", Magician:"distil:distils:distilled:distilling", Lover:"pare back:pares back:pared back:paring back"},
  "v:revolutionise":{Innocent:"change", Jester:"shake up:shakes up:shook up:shaking up", Creator:"reinvent", Explorer:"reshape"},
  "v:underscore":{Innocent:"stress", Outlaw:"hammer home:hammers home:hammered home:hammering home"},
  "v:highlight":{Innocent:"point out:points out:pointed out:pointing out", Outlaw:"call out:calls out:called out:calling out", Jester:"flag:flags:flagged:flagging", Lover:"spotlight", Magician:"illuminate"},
  /* adjectives, second set */
  "a:reliable":{Innocent:"trusty", Outlaw:"battle-tested", Magician:"steady", Jester:"rock-solid", Lover:"faithful", Explorer:"tried-and-tested"},
  "a:fast":{Innocent:"quick", Magician:"fleet", Caregiver:"quick", Creator:"nimble"},
  "a:clear":{Jester:"crystal-clear"},
  "a:powerful":{Innocent:"strong", Magician:"formidable"},
  "a:bold":{Innocent:"brave", Outlaw:"brazen", Magician:"audacious", Jester:"cheeky", Caregiver:"brave", Creator:"daring"},
  "a:creative":{Innocent:"imaginative", Outlaw:"unorthodox", Lover:"expressive", Caregiver:"resourceful"},
  "a:unique":{Innocent:"special", Jester:"one-of-a-kind", Caregiver:"special", Creator:"original"},
  "a:modern":{Innocent:"new", Magician:"present-day", Creator:"contemporary"},
  "a:complex":{Innocent:"tricky", Outlaw:"tangled", Jester:"fiddly", Lover:"nuanced", Creator:"layered"},
  "a:famous":{Innocent:"well-known", Creator:"celebrated"},
  "a:successful":{Outlaw:"winning", Jester:"winning", Lover:"fruitful", Caregiver:"thriving"},
  "a:careful":{Magician:"watchful", Creator:"deliberate", Explorer:"cautious"},
  "a:perfect":{Outlaw:"flawless", Magician:"flawless", Jester:"spot-on", Caregiver:"ideal", Explorer:"ideal"},
  "a:global":{Innocent:"worldwide", Creator:"worldwide"},
  "a:necessary":{Innocent:"needed", Lover:"needed", Caregiver:"needed", Creator:"needed", Explorer:"required"},
  "a:useful":{Innocent:"handy", Jester:"handy", Lover:"valuable", Caregiver:"helpful", Creator:"practical"},
  "a:hard":{Innocent:"tricky", Magician:"arduous", Lover:"taxing", Caregiver:"trying", Creator:"demanding"},
  "a:wide":{Innocent:"broad", Outlaw:"sweeping", Magician:"vast", Caregiver:"broad", Creator:"broad"},
  "a:final":{Innocent:"last", Outlaw:"last", Magician:"ultimate", Caregiver:"last", Creator:"last"},
  "a:complete":{Innocent:"whole", Lover:"whole", Caregiver:"whole", Creator:"entire"},
  "a:excellent":{Innocent:"lovely", Outlaw:"killer", Magician:"splendid", Caregiver:"fine", Creator:"superb", Explorer:"first-class"},
  "a:amazing":{Innocent:"wonderful", Creator:"remarkable"},
  "a:helpful":{Innocent:"kind", Lover:"kind", Creator:"useful"},
  "a:compelling":{Innocent:"interesting", Caregiver:"engaging", Creator:"vivid"},
  "a:impactful":{Innocent:"strong", Caregiver:"effective", Creator:"striking"},
  "a:innovative":{Innocent:"new", Outlaw:"unorthodox", Magician:"visionary", Jester:"clever", Caregiver:"fresh"},
  "a:robust":{Innocent:"strong", Outlaw:"tough", Magician:"enduring", Explorer:"hardy"},
  "a:seamless":{Innocent:"easy", Jester:"slick", Lover:"graceful", Caregiver:"smooth", Creator:"fluid"},
  "a:cutting-edge":{Innocent:"new", Outlaw:"bleeding-edge", Magician:"visionary", Creator:"pioneering"},
  "a:state-of-the-art":{Innocent:"newest", Outlaw:"bleeding-edge"},
  "a:world-class":{Innocent:"very good", Outlaw:"elite", Magician:"peerless", Jester:"ace", Creator:"first-rate"},
  "a:comprehensive":{Innocent:"complete", Creator:"full-scale"},
  "a:diverse":{Innocent:"varied", Magician:"manifold", Jester:"mixed", Caregiver:"varied", Creator:"many-sided"},
  "a:vibrant":{Innocent:"bright", Magician:"luminous", Lover:"rich", Explorer:"lively"},
  "a:stunning":{Innocent:"lovely", Magician:"luminous", Jester:"gorgeous", Caregiver:"lovely"},
  "a:passionate":{Innocent:"eager", Outlaw:"fierce", Magician:"fervent", Caregiver:"devoted", Creator:"driven", Explorer:"avid"},
  "a:proven":{Innocent:"trusted", Outlaw:"battle-tested", Jester:"tried-and-tested", Caregiver:"trusted", Creator:"tested", Explorer:"tried-and-tested"},
  "a:groundbreaking":{Innocent:"new", Outlaw:"rule-breaking", Magician:"visionary", Lover:"original", Caregiver:"fresh", Creator:"original"},
  "a:transformative":{Innocent:"big", Creator:"far-reaching", Explorer:"far-reaching"},
  /* nouns, second set */
  "n:business":{Innocent:"company", Outlaw:"operation", Jester:"shop"},
  "n:challenge":{Outlaw:"fight", Magician:"riddle", Creator:"puzzle"},
  "n:opportunity":{Innocent:"chance", Outlaw:"gap", Jester:"window", Lover:"chance", Caregiver:"chance", Creator:"opening"},
  "n:benefit":{Innocent:"plus", Outlaw:"payoff", Magician:"boon", Jester:"perk", Explorer:"gain"},
  "n:relationship":{Outlaw:"alliance", Jester:"rapport", Caregiver:"bond", Creator:"connection", Explorer:"link"},
  "n:process":{Jester:"routine", Creator:"workflow"},
  "n:standard":{Jester:"bar:bars", Caregiver:"benchmark"},
  "n:claim":{Innocent:"statement", Magician:"assertion", Caregiver:"statement", Creator:"statement"},
  "n:country":{Innocent:"land:lands", Creator:"land:lands"},
  "n:industry":{Innocent:"trade:trades", Magician:"field", Jester:"line of work:lines of work", Caregiver:"sector", Creator:"field"},
  "n:method":{Innocent:"way", Outlaw:"playbook", Explorer:"route"},
  "n:answer":{Innocent:"reply:replies"},
  "n:danger":{Magician:"peril", Caregiver:"hazard", Creator:"hazard"},
  "n:strength":{Outlaw:"muscle:muscle", Magician:"power:powers", Lover:"vigour:vigour"},
  "n:solution":{Innocent:"answer", Jester:"fix:fixes", Caregiver:"answer"},
  "n:journey":{Innocent:"trip", Jester:"trek", Creator:"path"},
  "n:landscape":{Innocent:"scene", Outlaw:"terrain", Jester:"scene"},
  "n:insight":{Innocent:"finding", Jester:"nugget", Caregiver:"finding", Creator:"finding"},
  "n:narrative":{Innocent:"story:stories", Jester:"yarn", Caregiver:"account", Explorer:"saga"},
  "n:engagement":{Innocent:"interest", Jester:"buzz:buzz", Caregiver:"involvement", Creator:"interaction"},
  "n:passion":{Innocent:"love", Outlaw:"fire", Magician:"spark", Caregiver:"care", Creator:"drive", Explorer:"zeal"},
  "n:innovation":{Innocent:"new idea:new ideas"},
  "n:offering":{Innocent:"range:ranges"},
  /* adverbs, second set */
  "r:quite":{Innocent:"rather"},
  "r:completely":{Innocent:"wholly", Outlaw:"utterly", Jester:"totally", Lover:"entirely"},
  "r:usually":{Innocent:"normally", Magician:"mostly", Jester:"mostly", Caregiver:"normally", Creator:"typically"}
};
