/* Generated by tools/build_sw.py. Do not edit by hand. */
const VERSION = "ae4f63d07d";
const CACHE = "lexiphon-" + VERSION;
const SHELL = [
  "./",
  "index.html",
  "manifest.json",
  "css/site.css?v=f55c2475",
  "css/studio.css?v=570e4f25",
  "js/page.js?v=1eadf0a2",
  "js/viewer.js?v=38aa58ba",
  "js/listen.js?v=c2c468d3",
  "js/lexicon.js?v=7a0beba2",
  "js/engine.js?v=fe467452",
  "js/brand.js?v=66087800",
  "js/studio.js?v=82323bc8",
  "js/pwa.js?v=4f5d0457",
  "fonts/fraunces-latin-full-italic.woff2",
  "fonts/fraunces-latin-full-normal.woff2",
  "fonts/hanken-grotesk-latin-wght-italic.woff2",
  "fonts/hanken-grotesk-latin-wght-normal.woff2",
  "images/favicon.svg",
  "images/apple-touch-icon.png",
  "images/icons/icon-192.png",
  "images/icons/icon-512.png",
  "images/icons/maskable-512.png",
  "images/emblems/caregiver.svg",
  "images/emblems/creator.svg",
  "images/emblems/explorer.svg",
  "images/emblems/hero.svg",
  "images/emblems/innocent.svg",
  "images/emblems/jester.svg",
  "images/emblems/lover.svg",
  "images/emblems/magician.svg",
  "images/emblems/outlaw.svg",
  "images/emblems/regular.svg",
  "images/emblems/ruler.svg",
  "images/emblems/sage.svg"
];
const HOME = new URL("./", self.registration.scope).href;

self.addEventListener("install", (event) => {
  event.waitUntil(
    caches.open(CACHE)
      .then((cache) => cache.addAll(SHELL.map((u) => new Request(u, { cache: "reload" }))))
      .then(() => self.skipWaiting())
  );
});

self.addEventListener("activate", (event) => {
  event.waitUntil(
    caches.keys()
      .then((keys) => Promise.all(keys.filter((k) => k.startsWith("lexiphon-") && k !== CACHE).map((k) => caches.delete(k))))
      .then(() => self.clients.claim())
  );
});

function timeout(promise, ms) {
  return new Promise((resolve, reject) => {
    const t = setTimeout(() => reject(new Error("timeout")), ms);
    promise.then((r) => { clearTimeout(t); resolve(r); }, (e) => { clearTimeout(t); reject(e); });
  });
}

async function pageRequest(request) {
  const cache = await caches.open(CACHE);
  try {
    const response = await timeout(fetch(request), 4000);
    if (response && response.ok) { cache.put(HOME, response.clone()); cache.put(request, response.clone()); }
    return response;
  } catch (error) {
    const hit = (await cache.match(request)) || (await cache.match(HOME));
    if (hit) return hit;
    throw error;
  }
}

async function assetRequest(request) {
  const cache = await caches.open(CACHE);
  const hit = await cache.match(request);
  if (hit) return hit;
  const response = await fetch(request);
  if (response && response.ok && response.type === "basic") cache.put(request, response.clone());
  return response;
}

self.addEventListener("fetch", (event) => {
  const request = event.request;
  if (request.method !== "GET" || request.headers.has("range")) return;
  const url = new URL(request.url);
  if (url.origin !== self.location.origin || url.pathname.endsWith("/sw.js")) return;
  event.respondWith(request.mode === "navigate" ? pageRequest(request) : assetRequest(request));
});
