#!/usr/bin/env python3
"""Writes sw.js, the service worker that keeps the site working offline and makes repeat visits fast.

It is generated so that it cannot drift from the page: the shell list comes from index.html and from the asset folders,
and the cache name carries a hash of every shell file, so any change to the site replaces the old cache on the next visit.

  python3 tools/build_sw.py

Run it again after any change to index.html, css/, js/, fonts/, the emblems, textures, or switch sounds.
Strategy: pages are fetched from the network first (with a short timeout) and fall back to the cache when offline;
everything else is served from the cache first and stored on first use. Only same-origin GET requests are handled.
"""
import glob, hashlib, json, os, re

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
os.chdir(ROOT)

def shell():
    html = open("index.html", encoding="utf-8").read()
    urls = ["./", "index.html"]
    # css and script links exactly as the page writes them, version query included
    for u in re.findall(r'(?:href|src)="((?:css|js)/[^"]+)"', html):
        if "vendor/" not in u and u not in urls:
            urls.append(u)
    for pat in ("fonts/*.woff2", "images/favicon.svg", "images/apple-touch-icon.png", "images/walnut.jpg", "images/panel.png",
                "images/emblems/*.svg", "audio/fx/*.wav"):
        urls += sorted(glob.glob(pat))
    return urls

def digest(urls):
    h = hashlib.sha256()
    for u in urls:
        path = "index.html" if u == "./" else u.split("?")[0]
        h.update(u.encode())
        with open(path, "rb") as f:
            h.update(f.read())
    return h.hexdigest()[:10]

TEMPLATE = r'''/* Generated by tools/build_sw.py. Do not edit by hand. */
const VERSION = "__VERSION__";
const CACHE = "lexiphon-" + VERSION;
const SHELL = __SHELL__;
const HOME = new URL("./", self.registration.scope).href;

self.addEventListener("install", (event) => {
  event.waitUntil(
    caches.open(CACHE)
      .then((cache) => cache.addAll(SHELL.map((u) => new Request(u, { cache: "reload" }))))
      .then(() => self.skipWaiting())
  );
});

self.addEventListener("activate", (event) => {
  event.waitUntil(
    caches.keys()
      .then((keys) => Promise.all(keys.filter((k) => k.startsWith("lexiphon-") && k !== CACHE).map((k) => caches.delete(k))))
      .then(() => self.clients.claim())
  );
});

function timeout(promise, ms) {
  return new Promise((resolve, reject) => {
    const t = setTimeout(() => reject(new Error("timeout")), ms);
    promise.then((r) => { clearTimeout(t); resolve(r); }, (e) => { clearTimeout(t); reject(e); });
  });
}

async function pageRequest(request) {
  const cache = await caches.open(CACHE);
  try {
    const response = await timeout(fetch(request), 4000);
    if (response && response.ok) { cache.put(HOME, response.clone()); cache.put(request, response.clone()); }
    return response;
  } catch (error) {
    const hit = (await cache.match(request)) || (await cache.match(HOME));
    if (hit) return hit;
    throw error;
  }
}

async function assetRequest(request) {
  const cache = await caches.open(CACHE);
  const hit = await cache.match(request);
  if (hit) return hit;
  const response = await fetch(request);
  if (response && response.ok && response.type === "basic") cache.put(request, response.clone());
  return response;
}

self.addEventListener("fetch", (event) => {
  const request = event.request;
  if (request.method !== "GET" || request.headers.has("range")) return;
  const url = new URL(request.url);
  if (url.origin !== self.location.origin || url.pathname.endsWith("/sw.js")) return;
  event.respondWith(request.mode === "navigate" ? pageRequest(request) : assetRequest(request));
});
'''

def main():
    urls = shell()
    missing = [u for u in urls if not os.path.exists("index.html" if u == "./" else u.split("?")[0])]
    if missing:
        raise SystemExit("Missing files: " + ", ".join(missing))
    out = TEMPLATE.replace("__VERSION__", digest(urls)).replace("__SHELL__", json.dumps(urls, indent=2))
    with open("sw.js", "w", encoding="utf-8") as f:
        f.write(out)
    total = sum(os.path.getsize("index.html" if u == "./" else u.split("?")[0]) for u in urls if u != "./")
    print(f"sw.js written: {len(urls)} shell files, {total // 1024} KB, cache lexiphon-{digest(urls)}")

if __name__ == "__main__":
    main()
